2018-03-20 16:46:17,754 ERROR: Exception on /index [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/armageddion/Alfr3d/b3na/www/b3na_web_bottle/app/routes.py", line 34, in index
    devices = Device.query.filter_by(environment=env.name)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 1596, in filter_by
    for key, value in kwargs.items()]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/operators.py", line 344, in __eq__
    return self.operate(eq, other)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 180, in operate
    return op(self.comparator, *other, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 1039, in __eq__
    other, adapt_source=self.adapter))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 1372, in _optimized_compare
    state = attributes.instance_state(state)
AttributeError: 'unicode' object has no attribute '_sa_instance_state'
2018-03-20 16:47:15,587 INFO: B3na web startup [in /home/armageddion/Alfr3d/b3na/www/b3na_web_bottle/app/__init__.py:46]
2018-03-20 16:47:18,936 ERROR: Exception on /index [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/armageddion/Alfr3d/b3na/www/b3na_web_bottle/app/routes.py", line 34, in index
    devices = Device.query.filter_by(environment=env.name)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 1596, in filter_by
    for key, value in kwargs.items()]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/operators.py", line 344, in __eq__
    return self.operate(eq, other)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 180, in operate
    return op(self.comparator, *other, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 1039, in __eq__
    other, adapt_source=self.adapter))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 1372, in _optimized_compare
    state = attributes.instance_state(state)
AttributeError: 'unicode' object has no attribute '_sa_instance_state'
2018-03-20 16:48:12,633 INFO: B3na web startup [in /home/armageddion/Alfr3d/b3na/www/b3na_web_bottle/app/__init__.py:46]
2018-03-20 16:49:43,481 INFO: B3na web startup [in /home/armageddion/Alfr3d/b3na/www/b3na_web_bottle/app/__init__.py:46]
2018-03-20 16:52:47,030 INFO: B3na web startup [in /home/armageddion/Alfr3d/b3na/www/b3na_web_bottle/app/__init__.py:46]
